"""Add official fields

Revision ID: 233d28814cf7
Revises: 1bee1dc5e0c5
Create Date: 2026-01-11 10:59:50.690673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233d28814cf7'
down_revision: Union[str, Sequence[str], None] = '1bee1dc5e0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('prize_pool', sa.String(), nullable=True))
    op.add_column('events', sa.Column('organizer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'organizer_name')
    op.drop_column('events', 'prize_pool')
    # ### end Alembic commands ###
