"""add_created_at_to_sponsors

Revision ID: 440899d5c8e0
Revises: 0e96eecb3279
Create Date: 2026-01-12 18:35:26.508424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440899d5c8e0'
down_revision: Union[str, Sequence[str], None] = '0e96eecb3279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsors', 'created_at')
    # ### end Alembic commands ###
